baseURL = 'https://cumc-ubc.ca/'
languageCode = 'en-ca'
title = 'CUMC at UBC'
theme = 'ananke'
[params]
    subtitle = 'The greatest mathematics conference of the 21st century.'
  [params.contact]
    email = 'info@example.org'
    phone = '+1 202-555-121'

